# Generated by Django 5.1.7 on 2025-03-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='article',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='posts',
            name='media',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
