# Generated by Django 5.1.7 on 2025-04-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='industries',
        ),
    ]
