# Generated by Django 5.1.7 on 2025-03-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_article_alter_posts_media_and_more'),
        ('users', '0003_personalprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personalprofile'),
        ),
    ]
