# Generated by Django 5.1.7 on 2025-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='industries',
            field=models.TextField(blank=True, null=True),
        ),
    ]
