# Generated by Django 5.1.7 on 2025-06-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_industries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='media',
            new_name='pic1',
        ),
        migrations.AddField(
            model_name='posts',
            name='pic2',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='posts',
            name='pic3',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
