# Generated by Django 5.1.7 on 2025-03-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='profile',
        ),
    ]
