# Generated by Django 5.1.7 on 2025-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_media_posts_pic1_posts_pic2_posts_pic3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
