# Generated by Django 5.1.7 on 2025-10-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='hash',
            field=models.CharField(default=123),
            preserve_default=False,
        ),
    ]
