# Generated by Django 5.1.7 on 2025-08-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_sessions_is_paid'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontransactions',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mentors.sessions'),
            preserve_default=False,
        ),
    ]
