# Generated by Django 5.1.7 on 2025-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_sessiontransactions_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontransactions',
            name='currency',
            field=models.CharField(default='NGN'),
            preserve_default=False,
        ),
    ]
