# Generated by Django 5.1.7 on 2025-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_sessiontransactions_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCallbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_ref', models.CharField()),
                ('transaction_id', models.CharField()),
            ],
        ),
    ]
