# Generated by Django 5.1.7 on 2025-08-27 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_sessions_is_paid'),
        ('payments', '0004_transactioncallbacks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('successful', 'successful')], default='pending')),
                ('initiated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.sessions')),
            ],
        ),
    ]
