# Generated by Django 5.1.7 on 2025-09-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_stripetransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontransactions',
            name='central_amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
