# Generated by Django 5.1.7 on 2025-04-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='cover_photo',
            field=models.CharField(default='https://careernexus-storage1.s3.amazonaws.com/profile_pictures/ad7b2bc0-98b2-4d29-bc90-3d784ce22cc9career_nexus_default_dp.png', max_length=300),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='profile_photo',
            field=models.CharField(default='https://careernexus-storage1.s3.amazonaws.com/profile_pictures/ad7b2bc0-98b2-4d29-bc90-3d784ce22cc9career_nexus_default_dp.png', max_length=3000),
        ),
    ]
