# Generated by Django 5.1.7 on 2025-05-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personalprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='name',
            field=models.CharField(default='Unregistered', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(default='learner', max_length=20),
        ),
    ]
