# Generated by Django 5.1.7 on 2025-05-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_name_alter_personalprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='first_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='last_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='middle_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
