# Generated by Django 5.1.7 on 2025-05-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_personalprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='hash',
            field=models.CharField(default='#######################', max_length=300),
            preserve_default=False,
        ),
    ]
