# Generated by Django 5.1.7 on 2025-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otp_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
