# Generated by Django 5.1.7 on 2025-05-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_otp_email_otp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='industry',
            field=models.CharField(default='others', max_length=100),
        ),
    ]
