# Generated by Django 5.1.7 on 2025-05-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
