# Generated by Django 5.1.7 on 2025-05-23 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_otp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
