# Generated by Django 5.1.7 on 2025-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_users_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
