# Generated by Django 5.1.7 on 2025-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_users_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='country_code',
            field=models.CharField(default='+000', max_length=20),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=30),
        ),
    ]
