# Generated by Django 5.1.7 on 2025-05-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_personalprofile_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='cover_photo',
            field=models.CharField(default='https://careernexus-storage1.s3.amazonaws.com/cover_photos/70114098-5014-4eda-a725-5421792972dadefault_cp.jpeg', max_length=300),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='profile_photo',
            field=models.CharField(default='https://careernexus-storage1.s3.amazonaws.com/profile_pictures/4aaed37c-eb8b-400d-a73a-82574dccfb88default_pp.jpeg', max_length=3000),
        ),
    ]
