# Generated by Django 5.1.7 on 2025-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_personalprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='areas_of_expertise',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='current_job',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='mentorship_styles',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='resume',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='technical_skills',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='timezone',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
