# Generated by Django 5.1.7 on 2025-07-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_personalprofile_areas_of_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='areas_of_expertise',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='mentorship_styles',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='technical_skills',
            field=models.JSONField(default=list),
        ),
    ]
