# Generated by Django 5.1.7 on 2025-07-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_personalprofile_areas_of_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='availability',
            field=models.CharField(blank=True, null=True),
        ),
    ]
