# Generated by Django 5.1.7 on 2025-07-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_personalprofile_id_alter_personalprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='timezone',
            field=models.CharField(default='UTC'),
        ),
    ]
