# Generated by Django 5.1.7 on 2025-08-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_personalprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='job_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='message_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='push_notify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='show_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='show_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='weekly_summary',
            field=models.BooleanField(default=False),
        ),
    ]
