# Generated by Django 5.1.7 on 2025-08-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_users_email_notify_users_job_alerts_users_marketing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='session_rate',
            field=models.IntegerField(default=0),
        ),
    ]
