# Generated by Django 5.1.7 on 2025-09-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_disputetickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputetickets',
            name='admin_response',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='disputetickets',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('resolved', 'resolved'), ('closed', 'closed')], default='pending', max_length=50),
        ),
    ]
