# Generated by Django 5.1.7 on 2025-09-17 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_disputetickets_admin_response_disputetickets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='logo',
            field=models.CharField(default='https://careernexus-storage1.s3.amazonaws.com/profile_pictures/b86858f7-c77e-4c5f-9796-14f27c855f7cDefault_company_image.png', max_length=300),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='LinkedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_account', to=settings.AUTH_USER_MODEL)),
                ('main_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
