# Generated by Django 5.1.7 on 2025-10-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_personalprofile_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField()),
                ('interested_services', models.CharField(choices=[('hr_solutions', 'hr_solutions'), ('corporate_training', 'corporate_training'), ('L&D', 'L&D'), ('organizational_development', 'organizational_development')])),
                ('package', models.CharField(choices=[('basic', 'basic'), ('premium', 'premium'), ('inclusive', 'inclusive')])),
                ('message', models.TextField()),
            ],
        ),
    ]
