# Generated by Django 5.1.7 on 2025-10-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_corporateleads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateleads',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='corporateleads',
            name='message',
        ),
        migrations.RemoveField(
            model_name='corporateleads',
            name='package',
        ),
    ]
