# Generated by Django 5.1.7 on 2025-10-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_corporateleads_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateleads',
            name='interested_services',
            field=models.JSONField(),
        ),
    ]
