# Generated by Django 5.1.7 on 2025-10-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_corporateleads_interested_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateleads',
            name='interested_services',
        ),
    ]
