# Generated by Django 5.1.7 on 2025-10-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_corporateleads_interested_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateleads',
            name='interested_services',
            field=models.JSONField(default='Technology'),
            preserve_default=False,
        ),
    ]
