# Generated by Django 5.1.7 on 2025-10-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_corporateleads_interested_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateleads',
            name='package',
            field=models.CharField(blank=True, choices=[('basic', 'basic'), ('premium', 'premium'), ('inclusive', 'inclusive')], null=True),
        ),
    ]
