# Generated by Django 5.1.7 on 2025-05-07 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
                ('employment_type', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('description', models.TextField()),
                ('industry', models.TextField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
