# Generated by Django 5.1.7 on 2025-06-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPreferenceSuffix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=99)),
                ('preference_combination', models.CharField(max_length=500)),
            ],
        ),
    ]
