# Generated by Django 5.1.7 on 2025-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobpreferencesuffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='experience_level',
            field=models.CharField(default='entry', max_length=20),
            preserve_default=False,
        ),
    ]
