# Generated by Django 5.1.7 on 2025-10-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_savedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('draft', 'draft'), ('closed', 'closed')], default='active', max_length=15),
            preserve_default=False,
        ),
    ]
