# Generated by Django 5.1.7 on 2025-10-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('draft', 'draft'), ('closed', 'closed')], default='active', max_length=15),
        ),
    ]
