# Generated by Django 5.1.7 on 2025-12-11 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobapplication_applied_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='application_deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 11, 15, 24, 33, 247164, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
