# Generated by Django 5.1.7 on 2025-04-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.CharField(default='NA', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='NA', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.CharField(default='NA', max_length=1000),
            preserve_default=False,
        ),
    ]
