# Generated by Django 5.1.7 on 2025-08-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_projectcatalogue_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcatalogue',
            name='download_material',
            field=models.CharField(blank=True, null=True),
        ),
    ]
