# Generated by Django 5.1.7 on 2025-08-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_projectcatalogue_download_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcatalogue',
            name='image',
            field=models.CharField(default='https://careernexus-storage1.s3.amazonaws.com/portfolio/image/6229255a-7c60-4f15-b932-39c525350c86default_portfolio.png'),
        ),
    ]
