# Generated by Django 5.1.7 on 2025-08-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
