# Generated by Django 5.1.7 on 2025-07-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='time',
        ),
        migrations.AddField(
            model_name='sessions',
            name='session_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
