# Generated by Django 5.1.7 on 2025-07-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_remove_sessions_date_remove_sessions_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
