# Generated by Django 5.1.7 on 2025-07-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_sessions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='room_name',
            field=models.CharField(default='Room_adca1405-8024-4dfe-9770-48765d1e885b'),
            preserve_default=False,
        ),
    ]
