# Generated by Django 5.1.7 on 2025-08-15 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_sessions_room_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_saved', to=settings.AUTH_USER_MODEL)),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_saver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
