# Generated by Django 5.1.7 on 2025-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_savedmentors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
