# Generated by Django 5.1.7 on 2025-09-25 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_mentorrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EARN', 'EARN'), ('WITHDRAW', 'WITHDRAW')], max_length=20)),
                ('amount', models.IntegerField()),
                ('extra_data', models.JSONField(default={})),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
