# Generated by Django 5.1.7 on 2025-09-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_mentorvault_vaulttransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaulttransactions',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
    ]
