# Generated by Django 5.1.7 on 2025-09-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_alter_vaulttransactions_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorvault',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
