# Generated by Django 5.1.7 on 2025-09-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0010_alter_mentorvault_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaulttransactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
