# Generated by Django 5.1.7 on 2025-10-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0011_alter_vaulttransactions_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
