# Generated by Django 5.1.7 on 2025-11-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0012_sessions_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_sessions', to='mentors.sessions')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.sessions')),
            ],
        ),
    ]
