# Generated by Django 5.1.7 on 2025-11-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0013_invitedsessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitedsessions',
            name='invitee',
        ),
    ]
