# Generated by Django 5.1.7 on 2025-11-11 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0014_remove_invitedsessions_invitee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedsessions',
            name='invitee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invited_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
