# Generated by Django 5.1.7 on 2025-05-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_information_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countrycodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=20)),
                ('permitted', models.BooleanField(default=True)),
            ],
        ),
    ]
