# Generated by Django 5.1.7 on 2025-09-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
