# Generated by Django 5.1.7 on 2025-11-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_chatroom_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='page',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='route',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
