# Generated by Django 5.1.7 on 2025-11-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_page_notification_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='obj_id',
            field=models.CharField(null=True),
        ),
    ]
